### ISSUE TITLE
"SUBMIT" Button Stopped Working

### ISSUE THREAD

**Issue by machineghost** [iNdieboyjeff/IntelliReST#2]
Yesterday I was using your REST client in WebStorm, and it worked great.  It was super convenient to just be able to do my queries directly in my IDE.

... but then today the plug-in stopped working.  Or rather, the one button that mattered ("SUBMIT") stopped working.  Everything else works fine (well, except that the headers table is like 5px high, but I don't need custom headers).  However, when I click "SUBMIT", no matter what I set the other options to, nothing happens (the Response tab fields remain completely blank).

Is there any way to reset the plugin or otherwise fix it?  I've only used it for a day and already I'm missing it.

**Comment by indieboyalex** [comment]
@machineghost I've not experience any issues like this so would need to investigate.  Are you getting any errors within the IDE that might suggest an exception is being thrown anywhere?

**Comment by machineghost** [comment]
Nope.  If there's any way to check a debug log in Webstorm I'd be more than happy to.

**Comment by indieboyalex** [comment]
Unfortunately as I'm unable to reproduce this issue there isn't much I can do.
